version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: gormhandson
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE  --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 3s
      timeout: 10s
      retries: 5
