version: '2'

vars:
  GOOSEIO: -path=./tool

tasks:
  default:
    cmds:
      - task up
      - task dependencies
      - task init
      - task migration

  dependencies:
    desc: Install dependencies.
    cmds:
      # - cargo install tcpwait

  up:
    desc: Start database container.
    cmds:
      - docker-compose up -d
      - (which tcpwait 1> /dev/null && tcpwait localhost:${DB_PORT} || sleep 3)

  down:
    desc: Stop database container.
    cmds:
      - docker-compose down

  reset:
    desc: Reset database schema
    cmds:
      - MYSQL_PWD=${DB_PASS} mysql -u ${DB_USER} -h ${DB_HOST} -P ${DB_PORT} --protocol=tcp -e "DROP DATABASE IF EXISTS ${DB_NAME}"
      - MYSQL_PWD=${DB_PASS} mysql -u ${DB_USER} -h ${DB_HOST} -P ${DB_PORT} --protocol=tcp -e "CREATE DATABASE ${DB_NAME}"

  migration:
    desc: apply migrations.
    cmds:
      - migrate -database="mysql://${DB_USER}:${DB_PASS}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}" -path=migrations up

  run:
    desc: run example.
    cmds:
      - go run create.go

  debug:
    desc: run delve.
    cmds:
      - dlv debug create.go