BEGIN;

DROP DATABASE IF EXISTS `metas`;
DROP DATABASE IF EXISTS `comments`;
DROP DATABASE IF EXISTS `authors`;
DROP DATABASE IF EXISTS `post_tags`;
DROP DATABASE IF EXISTS `tags`;
DROP DATABASE IF EXISTS `posts`;

COMMIT;